mv ABOUT.CPP about.cpp 
mv ABOUT.H about.h
mv AXIDLG.CPP axidlg.cpp
mv AXISDLG.CPP axisdlg.cpp 
mv AXISDLG.H axisdlg.h
mv DIBSECT.CPP dibsect.cpp
mv DIBSECT.H dibsect.h
mv Dhlist.c dhlist.c
mv Dhlist.h dhlist.h
mv FLTMNGR.bak fltmngr.bak
mv GRNDLEVL.H grndlevl.h
mv MISSION.CPP mission.cpp
mv MISSION.H mission.h
mv MOVEABLE.bak moveable.bak
mv PILOT.bak pilot.bak
mv POLYDLG.CPP polydlg.cpp
mv POLYDLG.H polydlg.h
mv RPOINT.H rpoint.h
mv Rndrplyx.cpp rndrplyx.cpp
mv SCENARIO.CPP scenario.cpp
mv SCENARIO.H scenario.h
mv SIMFILEX.H simfilex.h
mv SIMGRAF.H simgraf.h
mv SIMMATH.CPP simmath.cpp
mv SIMMATH.H simmath.h
mv Sabred3d.cpp sabred3d.cpp
mv Sabrewin.cpp sabrewin.cpp
mv Sarray.cpp sarray.cpp
mv Sarray.h sarray.h
mv Sfltmdl.cpp sfltmdl.cpp
mv Sfltmdl.h sfltmdl.h
mv Simfilex.cpp simfilex.cpp
mv Smath.cpp smath.cpp
mv Smath.h smath.h
mv Spid.c spid.c
mv Spid.h spid.h
mv Spilcaps.h spilcaps.h
mv Splncaps.h splncaps.h
mv Sslewer.cpp sslewer.cpp
mv Sslewer.h sslewer.h
mv Stact.cpp stact.cpp
mv Stact.h stact.h
mv Starget.cpp starget.cpp
mv Starget.h starget.h
mv Stypes.h stypes.h
mv TARGET.CPP target.cpp
mv VALUES.H values.h
mv Winjoy.h winjoy.h
mv ZVEDIT.RC zvedit.rc
